services:
  gnva-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnva_app
    ports:
      - "0.0.0.0:3010:3000"
    environment:
      - MYSQL_DATABASE_URL=mysql://root@host.docker.internal:3307/gnva
      - SESSION_SECRET=9xCEJOBbdM6aKHl0mZPpr8LnAFtYNfkG71uDoS2U4yhVvjgeswXiIT3q5WQzRc
      - APP_URL=http://192.168.1.219:3010
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - STORAGE_MODE=local
      - UPLOAD_DIR=/app/uploads
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./artifacts/gnva/uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
